name: Build

on:
  push:
  schedule:
    - cron: "0 0 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [thingy91_nrf9160ns, nrf9160dk_nrf9160ns]
    steps:
      - run: git clone --single-branch --branch master https://github.com/nrfconnect/sdk-nrf nrf
      - run: mkdir build
      - name: Build AT client sample
        run: |
          docker run --rm -v ${PWD}/nrf:/workdir/ncs/nrf \
            coderbyheart/fw-nrfconnect-nrf-docker \
            /bin/bash -c 'cd ncs/nrf/samples/nrf9160/at_client && west build -p always -b ${{ matrix.board }}'
          cp nrf/samples/nrf9160/at_client/build/zephyr/merged.hex build/at_client-${{ matrix.board }}.hex
      - uses: actions/upload-artifact@v2
        with:
          name: at_client-${{ matrix.board }}
          path: |
            build/at_client-*.hex

      - name: Publish HEX files
        run: |
          echo "machine github.com login accesskey password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          cd build
          touch .nojekyll
          git init
          git add -A
          git commit -m "Update HEX files"
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
